<?php
/**
 * @author Webtrekk Team
 * @copyright Copyright (c) 2016 Webtrekk GmbH (https://www.webtrekk.com)
 * @package Webtrekk_TagIntegration
 */
?>
<?php /** @var $this \Webtrekk\TagIntegration\Block\TIDatalayer **/ ?>
<!-- Webtrekk TagIntegration DataLayer -->
<script type="text/javascript">
	window._ti = <?php echo $this->getDataLayer(); ?>;
</script>
<!-- End Webtrekk TagIntegration DataLayer -->